### ISSUE TITLE
[er-2] - notification pada fitur tambah berita

### ISSUE THREAD

**Issue by FransiskaMaya** [aryogprakoso/Tugas-Manpro-PU#2]
di bagian artikel, kalau kita membuat artikel baru, akan muncul notification "Artikel berhasil ditambahkan".
sedangkan di bagian berita, kalau kita membuat artikel baru, tidak muncul notification pemberitahuan seperti di bagian artikel. mendingan ditambahin notification aja, supaya ada kesamaan antar-page.

**Comment by dealverina** [comment]
notification berita sudah ditambahkan
