### ISSUE TITLE
[er-3] edit berita

### ISSUE THREAD

**Issue by FransiskaMaya** [aryogprakoso/Tugas-Manpro-PU#3]
edit berita kalau di klik, form bagian judul dan artikelnya kosong. jadi seperti harus ngetik dari awal.

**Comment by FransiskaMaya** [comment]
[update]

form bagian judul dan artikel sudah ada, namun saat pilih save, akan langsung 404 Page Not Found

**Comment by dealverina** [comment]
edit berita sudah benar :)
