### ISSUE TITLE
[er-7] upload foto

### ISSUE THREAD

**Issue by FransiskaMaya** [aryogprakoso/Tugas-Manpro-PU#7]
a. bagian upload gambar, ekstensi yg bisa diupload cuma jpg sama jpeg ya?
- kalau mmg dibatasi cuma jpg dan jpeg, mending ditulis. dan ada error message kl format ga sesuai
- kalau mau di extend, bisa ditambah format .bmp sama .gif .png dll (yg masih berhubungan dgn image)

b. terus, kok kalau upload image, nama file imagenya ada karakter khusus (!@#$%^&*) dia gamau ketampil ya, sudah mau masuk folder uploads, sudah masuk database, cuma gambar tidak muncul (seperti corrupt)

c. nama file image asli dengan image yang berhasil masuk database berbeda

**Comment by AgungPrasetyaDK** [comment]
a. Extensi dari awal sudah bisa untuk upload extensi file gambar gif, jpeg, png, jpg, bmp, bisa dicoba langsung aja. :)

b. Sudah di fix ya.

c. Di database tidak menyimpan nama gambar, tapi mungkin nama gambar yang difolder assets/uploads memang berbeda sama file name aslinya, Saat menyimpan gambar file name memang akan direname menjadi timestamp+nama_asli menggunakan bantuan fungsi time(). dari helper CI. Kalo untuk timestampnya cara kerja dan formatnya bagaimana bisa keluar angka-angka seperti itu kurang tau juga. Tujuan nama file direname +timestamp itu agar semua file yang masuk itu namanya unique dan ga ada yang sama.
